config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
  end
  resources :posts
  devise_for :users

  authenticated :user, lambda {|u| u.role == :editor} do
    root 'posts#index', as: :editor_path
  end

  authenticated :user, lambda {|u| u.role == :company_admin} do
    root 'admin/users#index', as: :admin_path
  end

  root 'posts#index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/user.rb
class Admin::User < User
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  ################################################################################ 
  ## PeterGate Roles
  ## The :user role is added by default and shouldn't be included in this list.
  petergate(roles: [:company_admin, :editor], multiple: true)
  ################################################################################
  has_many :posts 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]
  access company_admin: :all 

  # GET /admin/users
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  def create
    @admin_user = Admin::User.new(admin_user_params)

    if @admin_user.save
      redirect_to @admin_user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /admin/users/1
  def update
    if @admin_user.update(admin_user_params)
      redirect_to @admin_user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/users/1
  def destroy
    @admin_user.destroy
    redirect_to admin_users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def admin_user_params
      params.require(:admin_user).permit(:email, :password, :password_confirmation, roles: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]
  before_action :set_user_post, only: [:edit, :update, :destroy]
  access all: [:index], user: [:index, :show], editor: :all 

  # GET /posts
  def index
    @posts = Post.all
  end

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_user_post
    @post = current_user.posts.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def post_params
    params.require(:post).permit(:title, :description, :user_id)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/users/_form.html.slim
= form_for @admin_user do |f|
  - if @admin_user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@admin_user.errors.count, "error")} prohibited this admin_user from being saved:"
      ul
        - @admin_user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :email
    = f.text_field :email
  - if @admin_user.new_record? || params[:passwd]
    .field
      = f.label :password
      = f.text_field :password
    .field
      = f.label :password_confirmation
      = f.text_field :password_confirmation
  .field
    = f.label :roles
    = f.select :roles, [:editor, :company_admin], {}, {multiple: true}
  .actions = f.submit

app/views/admin/users/edit.html.slim
h1 Editing admin_user

== render 'form'

= link_to 'Show', @admin_user
'|
= link_to 'Back', admin_users_path

app/views/admin/users/index.html.slim
h1 Admin Users

table.table.table-striped
  thead
    tr
      th Email
      th Password
      th Password confirmation
      th Roles
      th
      th
      th

  tbody
    - @admin_users.each do |admin_user|
      tr
        td = admin_user.email
        td = admin_user.password
        td = admin_user.password_confirmation
        td = admin_user.roles
        td = link_to 'Show', admin_user
        td = link_to 'Edit', edit_admin_user_path(admin_user)
        td = link_to 'Destroy', admin_user, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New User', new_admin_user_path

app/views/admin/users/new.html.slim
h1 New admin_user

== render 'form'

= link_to 'Back', admin_users_path

app/views/admin/users/show.html.slim
p
  strong Email:
  = @admin_user.email
p
  strong Password:
  = @admin_user.password
p
  strong Password confirmation:
  = @admin_user.password_confirmation
p
  strong Roles:
  = @admin_user.roles

= link_to 'Edit', edit_admin_user_path(@admin_user)
'|
= link_to 'Back', admin_users_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DpBlogPresentation</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <% if current_user %>
              <%= link_to "logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
            <% else %>
              <%= link_to "login", new_user_session_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "posts", posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <% if logged_in?(:company_admin) %>
              <%= link_to "users", admin_users_path, class: "nav-link" %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
    <div class='container'>
      <div class='row'>
        <div class='col-md-12'>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
      <div class='row'>
        <div class='col-md-12'>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions = f.submit

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

= link_to 'Show', @post
'|
= link_to 'Back', posts_path

app/views/posts/index.html.slim
h1 News Feed 

table.table.table-striped
  thead.thead-inverse
    tr
      th Title
      th Description
      th Author
      th
      - if logged_in?(:editor)
        th
        th

  tbody
    - @posts.each do |post|
      tr
        td = post.title
        td = post.description
        td = post.user.email
        td = link_to 'Show', post
        - if logged_in?(:editor)
          td = link_to 'Edit', edit_post_path(post)
          td = link_to 'Destroy', post, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Post', new_post_path if logged_in?(:editor)

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
h2
  = @post.title
blockquote.blockquote
  h6
    = @post.description
  p
    = "by - " + @post.user.email
= link_to 'Edit', edit_post_path(@post), class: "btn btn-warning-outline" if logged_in?(:editor)
= link_to 'Back', posts_path, class: "btn btn-primary-outline"